name: LaTeX Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
      
    - name: Setup LaTeX environment
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended latexmk texlive-bibtex-extra biber
      
    - name: Install LaTeX packages
      run: |
        sudo apt-get install -y texlive-science texlive-lang-english texlive-latex-recommended texlive-fonts-extra texlive-xetex
        
    - name: Install fontawesome5 package
      run: |
        sudo apt-get install -y texlive-fonts-extra
        
    - name: Compile LaTeX
      run: |
        latexmk -pdf -interaction=nonstopmode -bibtex ./resume.tex 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
