name: LaTeX Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex  # Replace 'your_cv.tex' with the name of your main LaTeX file

    - name: Compile LaTeX
      run: |
        latexmk -pdf -interaction=nonstopmode resume.tex 

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Publish the compiled PDF in the root directory
