name: LaTeX Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Setup LaTeX environment
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended latexmk texlive-bibtex-extra biber
          
          # Install additional LaTeX packages if needed
          sudo apt-get install -y texlive-science texlive-lang-english texlive-fonts-extra texlive-xetex

          # Install fontawesome5 package
          sudo apt-get install -y texlive-fonts-extra
          
      - name: Compile LaTeX
        run: |
          latexmk -pdf -interaction=nonstopmode -bibtex ./resume.tex 

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Move PDF to deployment directory
        run: |
          mkdir -p deployment_directory
          mv resume.pdf deployment_directory/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deployment_directory
          publish_branch: gh-pages
          enable_jekyll: false
