name: build_and_deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: .
      TEX_FILE: resume.tex
      HTML_FILE: index.html
      MAKEFILE: Makefile
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Setup LaTeX environment
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended latexmk texlive-bibtex-extra biber
          sudo apt-get install -y texlive-science texlive-lang-english texlive-fonts-extra texlive-xetex
          sudo apt-get install -y texlive-fonts-extra
      
      - name: Compile LaTeX
        run: |
          make -C ${{ env.DIR }}
      
      - name: Move PDF and HTML to deployment directory
        run: |
          mkdir -p github_artifacts
          mv ${{ env.DIR }}/*.pdf ${{ env.DIR }}/*.html github_artifacts/
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: github_artifacts

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build_artifacts

      - name: Create deployment directory
        run: mkdir -p github_deploy
      
      - name: Move artifacts to deployment directory
        run: mv build_artifacts/* github_deploy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true

  copy_index_to_build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy index.html and Makefile to build branch
        run: |
          git checkout -b build
          git add index.html Makefile
          git commit -m "Add index.html and Makefile"
          git push origin build
